[package]
name = "rust_algorithm"
version = "0.1.0"
edition = "2024"

[dependencies]
leetcode = { path = "./leetcode" }
book = { path = "./book" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[workspace]
resolver = "3"
members = ["leetcode", "book"]